_wandb:
    value:
        cli_version: 0.18.6
        m: []
        python_version: 3.13.0
        t:
            "1":
                - 55
            "2":
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.13.0
            "5": 0.18.6
            "8":
                - 2
                - 5
            "12": 0.18.6
            "13": darwin-arm64
alpha:
    value: 0.1
epochs:
    value: 1000000
epsilon:
    value: 0.1
gamma:
    value: 0.4
rows:
    value: 3
verification_epochs:
    value: 10
